spring.application.name=jdbc-client-demo

spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=user
spring.datasource.password=password

spring.h2.console.enabled=false

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/postgres/schema.sql
spring.sql.init.data-locations=classpath:db/postgres/data.sql
